### ISSUE TITLE
Problem in OpenHAB with bsbinput_string.js

### ISSUE THREAD

**Issue by Sprocket02** [fredlcore/bsb_lan#54]
Hello,

can you help me with this exception which has thrown by OpenHAB?

```
2020-01-25 15:21:09.732 [WARN ] [ab.binding.http.internal.HttpBinding] - Transformation 'JS(bsbinput_string.js)' threw an exception. [response=<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<title>BSB-LAN Web</title>
<style>A:link  {color:blue;text-decoration: none;} A:visited {color:blue;text-decoration: none;} A:hover {color:red;text-decoration: none;background-color:yellow} A:active {color:blue;text-decoration: none;} A:focus {color:red;text-decoration: none;}
input {width: 100%; box-sizing: border-box;} select {width: 100%;}</style>
</head><body>
<script>function set(line){
var value = document.getElementById('value'+line).value.replace(":", ".");
if(isNaN(value)==false){
window.open(document.getElementById('main_link').href+'S'+line+'='+document.getElementById('value'+line).value,'_self');
}}
function setbit(line){
var x=document.getElementById('value'+line); var value=0;
for (var i=0; i<x.options.length; i++) {
if(x.options[i].selected){
value=value+eval(x.options[i].value);
}}
window.open(document.getElementById('main_link').href+'S'+line+'='+value,'_self');
}</script>

<font face='Arial'>
<center><h1><A ID=main_link HREF='/'>BSB-LAN Web</A></h1></center>
<table width=80% align=center><tr bgcolor=#f0f0f0><td width=20% align=center><a href='/K'>Heizungsfunktionen</a></td><td width=20% align=center><font color=#000000>DS18B20 Sensoren</font></td><td width=20% align=center><font color=#000000>DHT22 Sensoren</font></td><td width=20% align=center><font color=#000000>Ausgabe Logdatei</font></td></tr><tr bgcolor=#f0f0f0><td width=20% align=center><a href='/C'>Einstellungen</a></td><td width=20% align=center><a href='http://github.com/fredlcore/bsb_lan/blob/master/command_ref/command_ref_DE.md'>URL-Befehle</a></td><td width=20% align=center><a href='http://github.com/fredlcore/bsb_lan/blob/master/HOWTO.md' target='new'>HowTo</a></td><td width=20% align=center><a href='http://github.com/fredlcore/bsb_lan/blob/master/FAQ.md' target='_new'>FAQ</a></td></tr></table><p></p><table align=center width=80%><tr><td>

<tr><td>
8005 Status -  Status Kessel: 175 - Freigegeben für HK
</td><td>
<select id='value8005'>
<option value='0'>---</option>
<option value='1'>STB angesprochen</option>
<option value='2'>Störung</option>
<option value='3'>Wächter angesprochen</option>
<option value='4'>Handbetrieb aktiv</option>
<option value='5'>Schornsteinfegerfkt, Vollast</option>
<option value='6'>Schornsteinfegerfkt, Teillast</option>
<option value='7'>Schornsteinfegerfkt aktiv</option>
<option value='8'>Gesperrt, Manuell</option>
<option value='9'>Gesperrt, Automatisch</option>
<option value='10'>Gesperrt</option>
<option value='11'>Anfahrentlastung</option>
<option value='12'>Anfahrentlastung, Teillast</option>
<option value='13'>Rückl’begrenzung</option>
<option value='14'>Rückl’begrenzung, Teillast</option>
<option value='15'>Freigegeben</option>
<option value='16'>Freigegeben, Teillast</option>
<option value='17'>Nachlauf aktiv</option>
<option value='18'>In Betrieb</option>
<option value='19'>Freigegeben</option>
<option value='20'>Minimalbegrenzung</option>
<option value='21'>Minimalbegrenzung, Teillast</option>
<option value='22'>Minimalbegrenzung aktiv</option>
<option value='23'>Anlagenfrostschutz aktiv</option>
<option value='24'>Frostschutz aktiv</option>
<option value='25'>Aus</option>
<option value='59'>Ladung Pufferspeicher</option>
<option value='123'>STB Test aktiv</option>
<option value='166'>In Betrieb für Heizkreis</option>
<option value='167'>In Teillastbetrieb für HK</option>
<option value='168'>In Betrieb für Trinkwasser</option>
<option value='169'>In Teillastbetrieb für TWW</option>
<option value='170'>In Betrieb für HK, TWW</option>
<option value='171'>In Teillastbetrieb für HK, TWW</option>
<option value='172'>Gesperrt, Feststoffkessel</option>
<option value='173'>Freigegeben für HK, TWW</option>
<option value='174'>Freigeben für TWW</option>
<option value='175'>Freigegeben für HK</option>
<option value='176'>Gesperrt, Außentemperatur</option>
<option value='198'>Gesperrt, Ökobetrieb</option>
</select></td><td></td></tr>
</td></tr></table>
</body>
</html>
]
org.openhab.core.transform.TransformationException: An error occurred while executing script. TypeError: Cannot read property "indexOf" from undefined in <eval> at line number 18
	at org.openhab.core.transform.TransformationHelper$TransformationServiceDelegate.transform(TransformationHelper.java:71) ~[bundleFile:?]
	at org.openhab.binding.http.internal.HttpBinding.execute(HttpBinding.java:218) [bundleFile:?]
	at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:146) [bundleFile:?]
	at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:169) [bundleFile:?]
```

This error always occurs when the "Status Kessel" has the value 175.

Regards

Sebastian

**Comment by fredlcore** [comment]
Sorry, I have no idea about OpenHab. You may have more luck in one of the OpenHab forums where the person who contributed the OpenHab binding could probably help. If you figure out where the error is and how to solve it, I'd be happy to fix this. For now, I'll close this issue, but feel free to re-open it if you have more information.
